# This is the primary configuration file for your Shopify app.

name = "Couture Search and Recos"
client_id = "8ba440c9bab74a1414d838c129248691"
application_url = "https://80716e0fe095.ngrok-free.app/admin"
embedded = false

[access_scopes]
# Scopes your app needs. Ensure they match your .env file.
scopes = "read_products,read_orders"

[auth]
redirect_urls = [
    "https://80716e0fe095.ngrok-free.app/auth/callback"
]

[webhooks]
api_version = "2025-04"

[pos]
embedded = true

[build]
include_config_on_deploy = true
command = "cd web && uvicorn main:app --host 0.0.0.0 --port {port}"