# This is the primary configuration file for your Shopify app.

name = "Couture Search and Recos"
client_id = "8ba440c9bab74a1414d838c129248691"
application_url = "https://f673388d8d70.ngrok-free.app/admin"
embedded = false

[access_scopes]
scopes = "read_products,read_orders,read_all_orders,write_metaobject_definitions,read_metaobjects,write_metaobjects"

[auth]
redirect_urls = [
    "https://f673388d8d70.ngrok-free.app/auth/callback"
]

[webhooks]
api_version = "2025-04"

[pos]
embedded = true

[build]
command = "cd web && uvicorn main:app --host 0.0.0.0 --port {port}"
