# This is the primary configuration file for your Shopify app.

name = "Couture Search and Recos"
client_id = "8ba440c9bab74a1414d838c129248691"
application_url = "https://cb694d296ae9.ngrok-free.app/install"
embedded = false # Your app will open in a new tab, not embedded in the admin

[access_scopes]
# Scopes your app needs. Ensure they match your .env file.
scopes = "read_products,read_orders"

[auth]
redirect_urls = [
    "https://cb694d296ae9.ngrok-free.app/auth/callback"
]

[webhooks]
api_version = "2025-04"

[pos]
embedded = false

[build]
include_config_on_deploy = true
