# shopify.app.toml
# THIS IS THE CORRECT AND FINAL VERSION.
# IT USES PLACEHOLDERS TO ALLOW THE CLI TO WORK DYNAMICALLY.

name = "Couture Search and Recos"
client_id = "8ba440c9bab74a1414d838c129248691"

# Use a placeholder. The CLI will replace it.
application_url = "https://example.com/admin"

# Your app IS embedded. This must be true.
embedded = true

[access_scopes]
scopes = "read_products,read_orders"

[auth]
redirect_urls = [
  "https://example.com/auth/callback"
]

# This tells the CLI how to start your Python server.
[build]
dev_command = "cd web && uvicorn main:app --host 127.0.0.1 --port {port}"

[webhooks]
api_version = "2025-04"

[pos]
embedded = false